/** First line of every generated file; also how orphans are recognized. */
export declare const MDX_GENERATED_MARKER = "// Generated by BractJS from ";
/** Split a leading `---` YAML block from the MDX body. */
export declare function splitFrontmatter(source: string, file: string): {
    data: Record<string, unknown>;
    body: string;
};
/** `meta()` descriptors from frontmatter `title` / `description`. */
export declare function frontmatterMeta(data: Record<string, unknown>): Array<Record<string, string>>;
/** The generated module for one MDX route, from the compiler's ESM output. */
export declare function mdxModuleSource(options: {
    sourceName: string;
    compiled: string;
    frontmatter: Record<string, unknown>;
    /** Import specifier of `app/mdx-components.tsx`, when it exists. */
    componentsImport?: string;
    /** The MDX body exports its own `meta`. */
    hasOwnMeta: boolean;
}): string;
export interface MdxCompileResult {
    /** Generated files that changed (appDir-relative). */
    written: string[];
    /** Generated files removed because their .mdx is gone. */
    removed: string[];
}
/**
 * Compile every `<appDir>/routes/**\/*.mdx` to its sibling `.mdx.tsx`, and
 * delete generated files whose `.mdx` is gone. No `.mdx` files → no compiler
 * needed. Throws on a compile error, on invalid frontmatter, and when a
 * `.mdx` and a `.tsx` route claim the same URL.
 */
export declare function compileMdxRoutes(appDir: string): Promise<MdxCompileResult>;
