import { existsSync, readFileSync, statSync } from "node:fs";
import { rm, utimes } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";

// MDX routes. Each `routes/**/*.mdx` compiles to a sibling `*.mdx.tsx` — a
// plain TSX route module the scanner maps to the same URL (`about.mdx.tsx` →
// `/about`). From there every path that already handles routes handles it:
// dev, `start`, the client build, HMR, the generated registries, the Node
// build and the compiled binary, none of which can run an MDX compiler. The
// generated files are gitignored and rewritten only when their content changes.

/** First line of every generated file; also how orphans are recognized. */
export const MDX_GENERATED_MARKER = "// Generated by BractJS from ";
/** Bumped when the generated module's shape changes, so old output recompiles. */
const FORMAT = "mdx-format:1";

type Compile = (source: string, options: Record<string, unknown>) => Promise<{ toString(): string }>;

async function loadCompiler(firstFile: string): Promise<Compile> {
  try {
    return ((await import("@mdx-js/mdx")) as { compile: Compile }).compile;
  } catch {
    throw new Error(
      `[bractjs] ${firstFile}: MDX routes need the MDX compiler. Install it in the app: bun add -d @mdx-js/mdx`,
    );
  }
}

/** Split a leading `---` YAML block from the MDX body. */
export function splitFrontmatter(
  source: string,
  file: string,
): { data: Record<string, unknown>; body: string } {
  const m = /^---\r?\n(?:([\s\S]*?)\r?\n)?---[ \t]*(?:\r?\n|$)/.exec(source);
  if (!m) return { data: {}, body: source };
  let data: unknown;
  try {
    data = m[1] ? Bun.YAML.parse(m[1]) : {};
  } catch (err) {
    throw new Error(`[bractjs] ${file}: invalid frontmatter: ${(err as Error).message}`);
  }
  if (data !== null && (typeof data !== "object" || Array.isArray(data))) {
    throw new Error(`[bractjs] ${file}: frontmatter must be key: value pairs`);
  }
  // Keep line numbers in compile errors pointing at the .mdx file.
  const blank = "\n".repeat(m[0].split("\n").length - 1);
  return { data: (data ?? {}) as Record<string, unknown>, body: blank + source.slice(m[0].length) };
}

/** `meta()` descriptors from frontmatter `title` / `description`. */
export function frontmatterMeta(data: Record<string, unknown>): Array<Record<string, string>> {
  const meta: Array<Record<string, string>> = [];
  if (typeof data.title === "string") meta.push({ title: data.title });
  if (typeof data.description === "string") meta.push({ name: "description", content: data.description });
  return meta;
}

/** The generated module for one MDX route, from the compiler's ESM output. */
export function mdxModuleSource(options: {
  sourceName: string;
  compiled: string;
  frontmatter: Record<string, unknown>;
  /** Import specifier of `app/mdx-components.tsx`, when it exists. */
  componentsImport?: string;
  /** The MDX body exports its own `meta`. */
  hasOwnMeta: boolean;
}): string {
  const DEFAULT = "export default function MDXContent(";
  if (!options.compiled.includes(DEFAULT)) {
    throw new Error(`[bractjs] ${options.sourceName}: unexpected MDX compiler output (no MDXContent export)`);
  }
  const lines = [
    `${MDX_GENERATED_MARKER}${options.sourceName}. Edit that file, not this one. (${FORMAT})`,
    "// @ts-nocheck",
    'import { createElement as __bractCreateElement } from "react";',
    options.componentsImport
      ? `import { components as __bractMdxComponents } from ${JSON.stringify(options.componentsImport)};`
      : "const __bractMdxComponents = undefined;",
    options.compiled.replace(DEFAULT, "function MDXContent("),
    `export const frontmatter = ${JSON.stringify(options.frontmatter)};`,
  ];
  const meta = frontmatterMeta(options.frontmatter);
  if (!options.hasOwnMeta && meta.length) {
    lines.push(`export function meta() {\n  return ${JSON.stringify(meta)};\n}`);
  }
  lines.push(
    "export default function MdxRoute(props) {",
    "  return __bractCreateElement(MDXContent, { ...props, components: { ...__bractMdxComponents, ...props.components } });",
    "}",
    "",
  );
  return lines.join("\n");
}

export interface MdxCompileResult {
  /** Generated files that changed (appDir-relative). */
  written: string[];
  /** Generated files removed because their .mdx is gone. */
  removed: string[];
}

/**
 * Compile every `<appDir>/routes/**\/*.mdx` to its sibling `.mdx.tsx`, and
 * delete generated files whose `.mdx` is gone. No `.mdx` files → no compiler
 * needed. Throws on a compile error, on invalid frontmatter, and when a
 * `.mdx` and a `.tsx` route claim the same URL.
 */
export async function compileMdxRoutes(appDir: string): Promise<MdxCompileResult> {
  const root = resolve(appDir);
  const result: MdxCompileResult = { written: [], removed: [] };
  if (!existsSync(join(root, "routes"))) return result;

  for await (const rel of new Bun.Glob("routes/**/*.mdx.tsx").scan(root)) {
    const abs = join(root, rel);
    if (existsSync(abs.slice(0, -".tsx".length))) continue;
    if (!readFileSync(abs, "utf8").startsWith(MDX_GENERATED_MARKER)) continue; // not ours
    await rm(abs, { force: true });
    result.removed.push(rel);
  }

  const componentsPath = ["mdx-components.tsx", "mdx-components.ts"]
    .map((f) => join(root, f))
    .find(existsSync);
  const componentsTime = componentsPath ? statSync(componentsPath).mtimeMs : 0;
  // Only files whose output is missing or older than the .mdx (or than
  // mdx-components) need the compiler — a production server that only
  // re-reads up-to-date output never loads it.
  const stale = [...new Bun.Glob("routes/**/*.mdx").scanSync(root)].sort().filter((rel) => {
    const abs = join(root, rel);
    if (!existsSync(abs + ".tsx")) return true;
    if (
      !readFileSync(abs + ".tsx", "utf8")
        .split("\n", 1)[0]
        .includes(FORMAT)
    )
      return true;
    const out = statSync(abs + ".tsx").mtimeMs;
    return out < statSync(abs).mtimeMs || out < componentsTime;
  });
  if (stale.length === 0) return result;
  const compile = await loadCompiler(stale[0]);

  // One broken file mustn't hold up the others: compile every stale file,
  // then report all failures together.
  const failures: string[] = [];
  for (const rel of stale) {
    try {
      const written = await compileOne(rel, root, compile, componentsPath);
      if (written) result.written.push(written);
    } catch (err) {
      failures.push((err as Error).message);
    }
  }
  if (failures.length === 1) throw new Error(failures[0]);
  if (failures.length > 1)
    throw new Error(`[bractjs] ${failures.length} MDX routes failed:\n${failures.join("\n")}`);
  return result;
}

/** An MDX body exports its own `meta` (outside fenced code blocks). */
export function exportsOwnMeta(body: string): boolean {
  const code = body.replace(/^(`{3,}|~{3,})[^\n]*\n[\s\S]*?^\1[ \t]*$/gm, "");
  return (
    /^export\s+(?:async\s+)?(?:const|let|var|function)\s+meta\b/m.test(code) ||
    /^export\s*\{[^}]*\bmeta\b[^}]*\}/m.test(code)
  );
}

/** Compile one stale route; returns its output path when the file changed. */
async function compileOne(
  rel: string,
  root: string,
  compile: Compile,
  componentsPath: string | undefined,
): Promise<string | null> {
  const abs = join(root, rel);
  const stem = abs.slice(0, -".mdx".length);
  for (const ext of [".tsx", ".ts"]) {
    if (existsSync(stem + ext)) {
      throw new Error(`[bractjs] ${rel} and ${relative(root, stem + ext)} are both routes for the same URL`);
    }
  }
  const { data, body } = splitFrontmatter(readFileSync(abs, "utf8"), rel);
  let compiled: string;
  try {
    compiled = String(
      await compile(body, { jsxImportSource: "react", development: false, outputFormat: "program" }),
    );
  } catch (err) {
    throw new Error(`[bractjs] ${rel}: ${(err as Error).message}`);
  }
  let componentsImport: string | undefined;
  if (componentsPath) {
    componentsImport = relative(dirname(abs), componentsPath).split("\\").join("/");
    if (!componentsImport.startsWith(".")) componentsImport = `./${componentsImport}`;
  }
  const out = mdxModuleSource({
    sourceName: basename(rel),
    compiled,
    frontmatter: data,
    componentsImport,
    hasOwnMeta: exportsOwnMeta(body),
  });
  const target = abs + ".tsx";
  if (existsSync(target) && readFileSync(target, "utf8") === out) {
    // Same output: mark it fresh, or the mtime check would recompile it forever.
    const now = new Date();
    await utimes(target, now, now);
    return null;
  }
  await Bun.write(target, out);
  return rel + ".tsx";
}
