import { join, resolve } from "node:path";
import { scanRoutes, layoutDirsFromFilePath, type RouteFile } from "../server/scanner.ts";
import { hasServerDirective } from "../shared/directives.ts";

// Codegen entry-points: `bun build --compile` can't statically trace
// `Bun.Glob` scans or `import(absPath)` calls, so we materialise the route /
// layout / action graph into static `import` statements at build time. The
// emitted files live at `<appDir>/_generated/{routes,actions}.ts` and are
// imported by the user-facing `app/server.ts` entrypoint.

// ── Path safety ────────────────────────────────────────────────────────────

// Allow ASCII filename characters, `/` for nested directories, `[`/`]` for
// file-based dynamic route syntax (`[id]`, `[...slug]`, `[[id]]`), and `(`/`)`
// for route-group folders (`(marketing)`). All emit sites wrap the path in
// JSON.stringify, but we still allowlist the charset as defense-in-depth
// against a hostile filename containing a backtick, $, quote, backslash, or
// whitespace breaking out of the generated literal. `..` as a whole segment is
// rejected separately below (path-traversal guard).
const SAFE_FILEPATH_RE = /^[A-Za-z0-9._\/\-\[\]()]+$/;

function assertSafeFilePath(filePath: string): void {
  if (!SAFE_FILEPATH_RE.test(filePath)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe file path: ${JSON.stringify(filePath)}`);
  }
  if (filePath.split("/").includes("..")) {
    throw new Error(`[bractjs] codegen: refusing to emit path with .. segment: ${JSON.stringify(filePath)}`);
  }
}

// Derive a JS identifier from an arbitrary relative path. Any character outside
// `[A-Za-z0-9_]` collapses to `_`. The leading digit (if any) gets an `_`
// prefix. This is purely for variable naming in the generated source; the
// authoritative key for the registry is the JSON-stringified relPath.
function pathToIdent(prefix: string, relPath: string): string {
  const safe = relPath.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(safe) ? `${prefix}__${safe}` : `${prefix}_${safe}`;
}

// ── Layout discovery ───────────────────────────────────────────────────────

/**
 * Find every `routes/<dir>/layout.tsx` (or `.ts`) that exists on disk for the
 * given set of routes. Mirrors the runtime probe in `resolveLayoutChain` but
 * runs once at codegen time so the generated registry is exhaustive. Layout
 * dirs are derived from each route's FILE path (via `layoutDirsFromFilePath`)
 * so route-group folders are covered identically to the runtime.
 */
async function collectLayouts(appDir: string, routes: RouteFile[]): Promise<string[]> {
  const layoutPaths = new Set<string>();
  for (const route of routes) {
    for (const dir of layoutDirsFromFilePath(route.filePath)) {
      for (const ext of ["tsx", "ts"]) {
        const rel = `routes/${dir}/layout.${ext}`;
        const abs = resolve(join(appDir, rel));
        if (await Bun.file(abs).exists()) {
          layoutPaths.add(rel);
        }
      }
    }
  }
  return [...layoutPaths].sort();
}

// ── Action discovery ───────────────────────────────────────────────────────


function isEligibleActionPath(rel: string): boolean {
  return (
    rel.endsWith(".server.ts") ||
    rel.endsWith(".server.tsx") ||
    rel.startsWith("routes/") ||
    rel.startsWith("routes\\")
  );
}

async function collectActionFiles(appDir: string): Promise<string[]> {
  const glob = new Bun.Glob("**/*.{ts,tsx}");
  const found: string[] = [];
  for await (const rel of glob.scan(appDir)) {
    if (!isEligibleActionPath(rel)) continue;
    // Skip the codegen output directory itself.
    if (rel.startsWith("_generated/")) continue;
    const abs = resolve(join(appDir, rel));
    let src: string;
    try {
      src = await Bun.file(abs).text();
    } catch {
      continue;
    }
    if (!hasServerDirective(src)) continue;
    // Normalise Windows separators to POSIX for the registry key.
    found.push(rel.split("\\").join("/"));
  }
  return found.sort();
}

// ── Generators ─────────────────────────────────────────────────────────────

const HEADER =
  "// Generated by `bractjs codegen` — do not edit manually.\n" +
  "// Static imports here let `bun build --compile` trace every route, layout,\n" +
  "// and server-action module instead of relying on runtime fs scans.\n" +
  "\n" +
  "/* eslint-disable */\n";

export interface RouteRegistryInput {
  appDir: string;
  routes: RouteFile[];
  layoutRelPaths: string[]; // e.g. ["routes/blog/layout.tsx"]
  hasRoot: boolean;         // true if appDir/root.tsx exists
}

export function generateRouteRegistry(input: RouteRegistryInput): string {
  const { routes, layoutRelPaths, hasRoot } = input;

  // ── Build the import statements ──
  const imports: string[] = [];
  const entries: string[] = [];

  if (hasRoot) {
    assertSafeFilePath("root.tsx");
    const ident = pathToIdent("mod", "root_tsx");
    imports.push(`import * as ${ident} from "../root.tsx";`);
    entries.push(`  ${JSON.stringify("root.tsx")}: ${ident},`);
  }

  for (const rel of layoutRelPaths) {
    assertSafeFilePath(rel);
    const ident = pathToIdent("mod", rel);
    imports.push(`import * as ${ident} from ${JSON.stringify("../" + rel)};`);
    entries.push(`  ${JSON.stringify(rel)}: ${ident},`);
  }

  for (const r of routes) {
    const rel = r.filePath.split("\\").join("/");
    assertSafeFilePath(rel);
    const ident = pathToIdent("mod", rel);
    imports.push(`import * as ${ident} from ${JSON.stringify("../" + rel)};`);
    entries.push(`  ${JSON.stringify(rel)}: ${ident},`);
  }

  // ── routeFiles array literal (mirrors scanRoutes output shape) ──
  const routeFilesLines: string[] = [];
  for (const r of routes) {
    const rel = r.filePath.split("\\").join("/");
    assertSafeFilePath(rel);
    const segments = JSON.stringify(r.segments);
    routeFilesLines.push(
      `  { filePath: ${JSON.stringify(rel)}, urlPattern: ${JSON.stringify(r.urlPattern)}, segments: ${segments} },`,
    );
  }

  return [
    HEADER,
    `import type { RouteFile, ModuleRegistry } from "@bractjs/bractjs";`,
    "",
    imports.join("\n"),
    "",
    "// Modules keyed by appDir-relative path. The framework looks up route,",
    "// layout, and root modules here at request time instead of doing a",
    "// dynamic `import(absPath)` call that would fail in a compiled binary.",
    "//",
    "// `ModuleRegistry` is intentionally `Record<string, RouteModule | Record<string, unknown>>`",
    "// — strict `RouteModule` typing would reject route files whose exports",
    "// (e.g. an ErrorBoundary typed for `{ error: Error }` instead of `{ error: unknown }`)",
    "// diverge slightly from the framework signature. Runtime behaviour is unchanged.",
    "export const moduleRegistry: ModuleRegistry = {",
    entries.join("\n"),
    "};",
    "",
    "export const routeFiles: RouteFile[] = [",
    routeFilesLines.join("\n"),
    "];",
    "",
  ].join("\n");
}

export interface ActionRegistryInput {
  appDir: string;
  actionRelPaths: string[];
}

export function generateActionRegistry(input: ActionRegistryInput): string {
  const { actionRelPaths } = input;

  const imports: string[] = [];
  const entries: string[] = [];

  for (const rel of actionRelPaths) {
    assertSafeFilePath(rel);
    const ident = pathToIdent("act", rel);
    imports.push(`import * as ${ident} from ${JSON.stringify("../" + rel)};`);
    entries.push(`  { relPath: ${JSON.stringify(rel)}, mod: ${ident} as Record<string, unknown> },`);
  }

  return [
    HEADER,
    imports.join("\n"),
    "",
    "// Server-action modules, statically imported so `bun build --compile`",
    "// traces them. The framework iterates this list and registers each",
    "// exported function under SHA-256(relPath + \"#\" + name) — identical to",
    "// the ID the client proxy plugin embeds in the bundled JS.",
    "export const actionModules: Array<{ relPath: string; mod: Record<string, unknown> }> = [",
    entries.join("\n"),
    "];",
    "",
  ].join("\n");
}

// ── Manifest codegen ───────────────────────────────────────────────────────

/**
 * Shape produced by `src/build/manifest.ts` (`RouteManifest`). Re-typed here
 * so the codegen module stays decoupled from the build pipeline.
 */
interface DiskManifest {
  version?: number;
  mode?: string;
  clientEntry: string;
  rootChunk?: string;
  routes: Record<string, { chunk: string; pattern: string }>;
}

/**
 * Convert the disk-format manifest (RouteManifest) into a TypeScript module
 * exporting a `ServerManifest` constant. This decouples the compiled-binary
 * server entry from the disk manifest — at startup it imports the constant
 * instead of reading `build/route-manifest.json`.
 */
export function generateManifestModule(disk: DiskManifest): string {
  // Mirror the RouteManifest → ServerManifest projection in serve.ts so the
  // compiled binary sees the same shape `buildFetchHandler` would have built.
  const projectedRoutes: Record<string, { file: string; chunk: string }> = {};
  for (const [pat, entry] of Object.entries(disk.routes ?? {})) {
    projectedRoutes[pat] = { file: entry.chunk, chunk: entry.chunk };
  }
  const projected = {
    clientEntry: disk.clientEntry,
    rootChunk: disk.rootChunk,
    routes: projectedRoutes,
  };
  // JSON.stringify is safe for embedding — all strings get properly escaped.
  // No template literals or backtick interpolation can leak through.
  return [
    HEADER,
    `import type { ServerManifest } from "@bractjs/bractjs";`,
    "",
    "// Snapshot of build/route-manifest.json, frozen into the binary so the",
    "// server never needs to read it from disk at startup.",
    `export const manifest: ServerManifest = ${JSON.stringify(projected, null, 2)};`,
    "",
  ].join("\n");
}

/**
 * Read `<buildDir>/route-manifest.json` and write
 * `<appDir>/_generated/manifest.ts`. Must run AFTER the client `Bun.build()`
 * step — chunk filenames are content-hashed and not known until then.
 */
export async function writeManifestModule(
  appDir: string,
  buildDir: string,
): Promise<string> {
  const absAppDir = resolve(appDir);
  const absBuildDir = resolve(buildDir);
  const src = join(absBuildDir, "route-manifest.json");
  const file = Bun.file(src);
  if (!(await file.exists())) {
    throw new Error(
      `[bractjs] manifest codegen: ${src} not found. Run the client build before manifest codegen.`,
    );
  }
  const disk = (await file.json()) as DiskManifest;
  const out = join(absAppDir, "_generated", "manifest.ts");
  await Bun.write(out, generateManifestModule(disk));
  return out;
}

// ── Driver ─────────────────────────────────────────────────────────────────

export interface CodegenResult {
  routesPath: string;
  actionsPath: string;
}

export async function writeModuleRegistries(appDir: string): Promise<CodegenResult> {
  const absAppDir = resolve(appDir);
  const routes = await scanRoutes(absAppDir);
  const layoutRelPaths = await collectLayouts(absAppDir, routes);
  const hasRoot =
    (await Bun.file(resolve(join(absAppDir, "root.tsx"))).exists()) ||
    (await Bun.file(resolve(join(absAppDir, "root.ts"))).exists());
  const actionRelPaths = await collectActionFiles(absAppDir);

  const routesSrc = generateRouteRegistry({ appDir: absAppDir, routes, layoutRelPaths, hasRoot });
  const actionsSrc = generateActionRegistry({ appDir: absAppDir, actionRelPaths });

  const outDir = resolve(join(absAppDir, "_generated"));
  const routesPath = join(outDir, "routes.ts");
  const actionsPath = join(outDir, "actions.ts");

  await Bun.write(routesPath, routesSrc);
  await Bun.write(actionsPath, actionsSrc);

  return { routesPath, actionsPath };
}
