import { join } from "node:path";
import { scanRoutes } from "../server/scanner.ts";
import type { Segment } from "../server/scanner.ts";
import { hashString } from "../build/hash.ts";

// Convert [param] / [[optional]] / [...catchAll] notation to :param colon-style.
function patternToColon(urlPattern: string): string {
  if (urlPattern === "") return "/";
  return "/" + urlPattern.split("/").map((seg) => {
    if (seg.startsWith("[...") && seg.endsWith("]")) return ":" + seg.slice(4, -1);
    if (seg.startsWith("[[") && seg.endsWith("]]")) return ":" + seg.slice(2, -2);
    if (seg.startsWith("[") && seg.endsWith("]")) return ":" + seg.slice(1, -1);
    return seg;
  }).join("/");
}

function paramsFromSegments(segments: Segment[]): string[] {
  return segments.flatMap((seg) =>
    typeof seg === "string" ? [] :
    "param" in seg ? [seg.param] :
    "optional" in seg ? [seg.optional] :
    [seg.catchAll],
  );
}

// Replace each :paramName segment with ${params.paramName} for template literals.
function substituteParams(pattern: string, params: string[]): string {
  const set = new Set(params);
  return pattern.split("/").map((seg) =>
    seg.startsWith(":") && set.has(seg.slice(1))
      ? "${params." + seg.slice(1) + "}"
      : seg,
  ).join("/");
}

// Allowed pattern: "/" + (segment | ":ident") (segments are filename-derived).
// Restricting upfront removes any chance that a hostile filename injects a
// backtick, ${ }, or quote into the generated TS source.
const SAFE_PATTERN_RE = /^\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*)(?:\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*))*$|^\/$/;
const SAFE_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;
// Same guard the module-registry codegen applies before emitting import paths.
// Parens are permitted for route-group folders like `(marketing)`; they are
// inert inside the double-quoted import string the codegen emits.
const SAFE_FILEPATH_RE = /^[A-Za-z0-9._\/\-\[\]()]+$/;

function assertSafePattern(pattern: string): void {
  if (!SAFE_PATTERN_RE.test(pattern)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe route pattern: ${JSON.stringify(pattern)}`);
  }
}
function assertSafeParam(name: string): void {
  if (!SAFE_IDENT_RE.test(name)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe param name: ${JSON.stringify(name)}`);
  }
}
function assertSafeFilePath(filePath: string): void {
  if (!SAFE_FILEPATH_RE.test(filePath) || filePath.split("/").includes("..")) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe file path: ${JSON.stringify(filePath)}`);
  }
}

function builderEntry(pattern: string, params: string[]): string {
  assertSafePattern(pattern);
  params.forEach(assertSafeParam);
  const key = JSON.stringify(pattern);
  if (params.length === 0) return "  " + key + ": () => " + key + " as const,";
  const paramType = params.map((p) => p + ": string").join("; ");
  const body = substituteParams(pattern, params);
  return "  " + key + ": (params: { " + paramType + " }) => `" + body + "` as const,";
}

function paramsTypeLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const dynamic = routes.filter((r) => r.params.length > 0);
  if (dynamic.length === 0) return "export type RouteParams<_T extends AppRoutes> = Record<never, never>;";
  const branches = dynamic
    .map((r) => {
      assertSafePattern(r.pattern);
      r.params.forEach(assertSafeParam);
      return "  T extends " + JSON.stringify(r.pattern) + " ? { "
        + r.params.map((p) => p + ": string").join("; ")
        + " } :";
    })
    .join("\n");
  return "export type RouteParams<T extends AppRoutes> =\n" + branches + "\n  Record<never, never>;";
}

// Replaced at the top of the generated file.
const HEADER =
  "// Generated by `bractjs codegen` — do not edit manually.\n" +
  "// Re-run with: bunx bractjs codegen\n" +
  "\n" +
  "/* eslint-disable */\n";

// `RouteSearchParamsMap` / `RouteContextMap` are owned by the package
// (`@bractjs/bractjs`) so users have a single stable module to augment. We do
// NOT seed per-route keys here: seeding `"/posts": Record<string,string>` would
// conflict with a user augmentation declaring `"/posts": { page: string }`
// (duplicate-property error). Instead `SearchParams<T>` / `Context<T>` fall back
// to the permissive default for any route the user hasn't augmented.
function searchParamsTypeLines(routes: Array<{ pattern: string }>): string {
  if (routes.length === 0) {
    return "export type SearchParams<_T extends AppRoutes> = Record<string, string>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      const key = JSON.stringify(r.pattern);
      // Use `extends Record<K, infer V>` rather than `keyof` + index access:
      // RouteSearchParamsMap may be `{}` (no user augmentation), and indexing an
      // empty interface — even inside a `K extends keyof M` guard — trips
      // TS2538 "cannot be used as an index type". The Record-infer form resolves
      // V only when the route is augmented, and falls back otherwise.
      return "  T extends " + key +
        " ? (RouteSearchParamsMap extends Record<" + key + ", infer V> ? V : Record<string, string>) :";
    })
    .join("\n");
  return [
    "// Augment RouteSearchParamsMap (on the package) to type a route's search params:",
    "//   declare module \"@bractjs/bractjs\" { interface RouteSearchParamsMap { \"/blog\": { page: string } } }",
    "export type SearchParams<T extends AppRoutes> =",
    branches,
    "  Record<string, string>;",
  ].join("\n");
}

// Per-route VALIDATED search shapes, inferred from each route's `searchSchema`
// export via type-only `typeof import(...)`. Routes without a schema fall back
// to the user's RouteSearchParamsMap augmentation, then a permissive record.
// This map feeds `Register.routes.searchOutput` → `useSearch`/`useSetSearch`/
// `<Link search>`; the legacy string-valued `search` member is untouched.
function searchOutputTypeLines(routes: Array<{ pattern: string; filePath: string }>): string {
  if (routes.length === 0) {
    return "export type GeneratedSearchOutput = Record<never, never>;";
  }
  const entries = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      assertSafeFilePath(r.filePath);
      const key = JSON.stringify(r.pattern);
      const spec = JSON.stringify("./" + r.filePath.split("\\").join("/"));
      return "  " + key + ": typeof import(" + spec + ") extends { searchSchema: infer S }\n" +
        "    ? InferSchemaOutput<S>\n" +
        "    : (RouteSearchParamsMap extends Record<" + key + ", infer V> ? V : Record<string, unknown>);";
    })
    .join("\n");
  return [
    "// Validated search shape per route, inferred from `searchSchema` exports.",
    "export type GeneratedSearchOutput = {",
    entries,
    "};",
    "",
    "/** Validated search object for a route — what `useSearch<T>()` returns. */",
    "export type SearchOutput<T extends AppRoutes> =",
    "  T extends keyof GeneratedSearchOutput ? GeneratedSearchOutput[T] : Record<string, unknown>;",
  ].join("\n");
}

function contextTypeLines(routes: Array<{ pattern: string }>): string {
  if (routes.length === 0) {
    return "export type Context<_T extends AppRoutes> = Record<string, unknown>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      const key = JSON.stringify(r.pattern);
      // See SearchParams above for why this uses `extends Record<K, infer V>`.
      return "  T extends " + key +
        " ? (RouteContextMap extends Record<" + key + ", infer V> ? V : Record<string, unknown>) :";
    })
    .join("\n");
  return [
    "// Augment RouteContextMap (on the package) to type a route's context:",
    "//   declare module \"@bractjs/bractjs\" { interface RouteContextMap { \"/blog\": { user: User } } }",
    "export type Context<T extends AppRoutes> =",
    branches,
    "  Record<string, unknown>;",
  ].join("\n");
}

// The `Register` augmentation: this is what wires the app's routes into the
// package's runtime helpers (<Link>, useNavigate, useParams, useSearchParams).
function registerAugmentationLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const paramEntries = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      r.params.forEach(assertSafeParam);
      const shape = r.params.length === 0
        ? "{}"
        : "{ " + r.params.map((p) => p + ": string").join("; ") + " }";
      return "      " + JSON.stringify(r.pattern) + ": " + shape + ";";
    })
    .join("\n");
  return [
    "// Registers this app's routes with BractJS. After this augmentation, <Link>,",
    "// useNavigate, useParams, and useSearchParams are type-safe against AppRoutes.",
    "declare module \"@bractjs/bractjs\" {",
    "  interface Register {",
    "    routes: {",
    "      routes: AppRoutes;",
    "      params: {",
    paramEntries,
    "      };",
    "      search: RouteSearchParamsMap;",
    "      searchOutput: GeneratedSearchOutput;",
    "    };",
    "  }",
    "}",
  ].join("\n");
}

// ── Freshness fingerprint ────────────────────────────────────────────────
// The generated file embeds a hash of its route patterns so the dev server can
// detect drift precisely (and skip rewrites when nothing changed, which would
// otherwise trigger an editor reload loop). Patterns are sorted everywhere so
// the output is identical across machines regardless of filesystem scan order.

const FINGERPRINT_RE = /^\/\/ bractjs:routes ([0-9a-f]+) \((\d+) routes?\)$/m;

/** Stable 8-hex fingerprint of a route-pattern set (order-independent). */
export function routesFingerprint(patterns: string[]): Promise<string> {
  return hashString([...patterns].sort().join("\n"));
}

/** Extract the fingerprint hash previously written into a generated file, or null. */
export function readFingerprint(src: string | null): string | null {
  if (!src) return null;
  const m = src.match(FINGERPRINT_RE);
  return m ? m[1] : null;
}

/**
 * A precise human-readable reason the generated types are stale, or null when
 * fresh. `patterns` must be colon-style (the form the generated file embeds);
 * prefer {@link explainStalenessForApp} which derives them for you.
 */
export async function explainStaleness(
  oldSrc: string | null,
  patterns: string[],
): Promise<string | null> {
  if (!oldSrc) return "route-types.gen.ts is missing — generating it";
  const current = await routesFingerprint(patterns);
  if (readFingerprint(oldSrc) === current) return null;
  // Recover the old pattern set from the union members to report add/remove
  // counts. The last member ends with `;`, so allow an optional trailing `;`.
  const old = new Set(
    [...oldSrc.matchAll(/^ {2}\| "([^"]+)";?$/gm)].map((m) => m[1]),
  );
  const now = new Set(patterns);
  const added = patterns.filter((p) => !old.has(p)).length;
  const removed = [...old].filter((p) => !now.has(p)).length;
  const parts: string[] = [];
  if (added) parts.push(`+${added} added`);
  if (removed) parts.push(`-${removed} removed`);
  const detail = parts.length ? ` (${parts.join(", ")})` : "";
  return `routes changed since last codegen${detail} — regenerating`;
}

/** Colon-style route patterns for an app dir (the form the generated file uses). */
export async function routePatternsForApp(appDir: string): Promise<string[]> {
  const routeFiles = await scanRoutes(appDir);
  return routeFiles.map((r) => patternToColon(r.urlPattern));
}

/** {@link explainStaleness} against the current generated file + route set on disk. */
export async function explainStalenessForApp(
  appDir: string,
  outPath?: string,
): Promise<string | null> {
  const dest = outPath ?? join(appDir, "route-types.gen.ts");
  const existing = await Bun.file(dest).text().catch(() => null);
  return explainStaleness(existing, await routePatternsForApp(appDir));
}

export async function generateRouteTypes(appDir: string): Promise<string> {
  const routeFiles = await scanRoutes(appDir);
  const routes = routeFiles
    .map((r) => ({
      pattern: patternToColon(r.urlPattern),
      params: paramsFromSegments(r.segments),
      filePath: r.filePath,
    }))
    // Deterministic order independent of filesystem scan order, so the output
    // is byte-identical across machines (and the idempotent write works).
    .sort((a, b) => a.pattern.localeCompare(b.pattern));

  const union = routes.length > 0
    ? routes.map((r) => {
        assertSafePattern(r.pattern);
        return "  | " + JSON.stringify(r.pattern);
      }).join("\n")
    : "  never";

  const builderEntries = routes.map((r) => builderEntry(r.pattern, r.params)).join("\n");

  // `RouteSearchParamsMap` / `RouteContextMap` are imported from the package so
  // the local `SearchParams<T>` / `Context<T>` reference the same interfaces the
  // user augments via `declare module "@bractjs/bractjs"`. `InferSchemaOutput`
  // derives each route's validated search shape from its `searchSchema` export.
  const IMPORTS = 'import type { RouteSearchParamsMap, RouteContextMap, InferSchemaOutput } from "@bractjs/bractjs";';

  // Freshness breadcrumb: lets the dev server detect drift without re-deriving
  // the whole file, and lets writeRouteTypes skip identical writes.
  const fingerprint = await routesFingerprint(routes.map((r) => r.pattern));
  const FINGERPRINT = `// bractjs:routes ${fingerprint} (${routes.length} route${routes.length === 1 ? "" : "s"})`;

  return [
    HEADER,
    FINGERPRINT,
    IMPORTS,
    "",
    "export type AppRoutes =",
    union + ";",
    "",
    paramsTypeLines(routes),
    "",
    searchParamsTypeLines(routes),
    "",
    searchOutputTypeLines(routes),
    "",
    contextTypeLines(routes),
    "",
    "export type TypedLoaderArgs<T extends AppRoutes> = {",
    "  request: Request;",
    "  params: RouteParams<T>;",
    "  context: Context<T>;",
    "  search: T extends keyof GeneratedSearchOutput ? GeneratedSearchOutput[T] : Record<string, unknown>;",
    "};",
    "export type TypedActionArgs<T extends AppRoutes> =",
    "  TypedLoaderArgs<T> & { formData: FormData };",
    "",
    "/** Loader args fully typed for a route literal: `loader(args: LoaderArgsFor<\"/posts\">)`. */",
    "export type LoaderArgsFor<T extends AppRoutes> = TypedLoaderArgs<T>;",
    "/** Action args fully typed for a route literal: `action(args: ActionArgsFor<\"/posts\">)`. */",
    "export type ActionArgsFor<T extends AppRoutes> = TypedActionArgs<T>;",
    "",
    "/** A locale-prefixed variant of a route (E2 i18n routing). */",
    "export type LocalizedRoute<T extends AppRoutes> = `/${string}${T}`;",
    "",
    "export const routes = {",
    builderEntries,
    "} as const;",
    "",
    // No routes → AppRoutes is `never`; nothing to register.
    routes.length > 0 ? registerAugmentationLines(routes) : "",
    "",
  ].join("\n");
}

export async function writeRouteTypes(
  appDir: string,
  outPath?: string,
): Promise<{ dest: string; written: boolean }> {
  const dest = outPath ?? join(appDir, "route-types.gen.ts");
  const next = await generateRouteTypes(appDir);
  // Skip the write (and the log, and the resulting file-watcher event) when the
  // content is unchanged — otherwise auto-codegen in dev would loop the editor.
  const existing = await Bun.file(dest).text().catch(() => null);
  if (existing === next) return { dest, written: false };
  await Bun.write(dest, next);
  console.log("[bract] codegen →", dest);
  return { dest, written: true };
}
