import { join } from "node:path";
import { writeModuleRegistries } from "./module-registry.ts";
import { writeRouteTypes } from "./route-codegen.ts";

// Stub manifest written so `app/server.ts` (the compile/`start` entry, which
// statically imports `_generated/manifest.ts`) typechecks before a real build
// exists. `bractjs codegen:manifest` overwrites it with the built manifest.
const MANIFEST_STUB = [
  "// Stub manifest — replaced by `bractjs codegen:manifest` after running",
  "// `bractjs build`. Lets `app/server.ts` typecheck before the first build.",
  `import type { ServerManifest } from "@bractjs/bractjs";`,
  `export const manifest: ServerManifest = { clientEntry: "/build/client/client.js", routes: {} };`,
  "",
].join("\n");

// Ambient declarations for stylesheet imports. Bun extracts CSS at build time,
// but TypeScript needs to be told these specifiers resolve to something —
// otherwise `import styles from "./x.module.css"` is a TS2307 error in every
// app. `*.module.css` yields the scoped class-name map Bun generates; plain
// stylesheets are side-effect-only imports.
const CSS_TYPES = [
  "// Generated by BractJS — do not edit.",
  "// Ambient types for stylesheet imports handled by the bundler.",
  "",
  'declare module "*.module.css" {',
  "  /** Scoped class names: original name → hashed name generated at build time. */",
  "  const classes: Readonly<Record<string, string>>;",
  "  export default classes;",
  "}",
  "",
  'declare module "*.css" {',
  "  /** Plain stylesheets are imported for their side effect (extraction + linking). */",
  "  const css: void;",
  "  export default css;",
  "}",
  "",
].join("\n");

/**
 * Seed `<appDir>/_generated/` so `app/server.ts` typechecks before the first
 * build: route/action registries (`routes.ts`, `actions.ts`), typed routes
 * (`route-types.gen.ts`), a manifest stub (`manifest.ts`), and ambient CSS
 * module types (`css.d.ts`). The generated files are gitignored and regenerated
 * on demand — this is what makes a fresh clone (or CI) typecheck without first
 * running a build.
 *
 * Shared by `bractjs new` (scaffold seeding) and `bractjs codegen:seed`.
 *
 * @param appDir absolute path to the app directory (the one containing `routes/`).
 */
export async function seedGenerated(appDir: string): Promise<void> {
  await writeModuleRegistries(appDir);
  await writeRouteTypes(appDir);
  await Bun.write(join(appDir, "_generated", "manifest.ts"), MANIFEST_STUB);
  await Bun.write(join(appDir, "_generated", "css.d.ts"), CSS_TYPES);
}

/**
 * Seed only what's missing so `<appDir>/server.ts` is importable (its static
 * `_generated/*` imports resolve). Unlike seedGenerated, this never overwrites
 * an existing `manifest.ts` — `bractjs codegen:manifest` may have snapshotted a
 * real build there. Returns true when anything was written.
 */
export async function seedGeneratedIfMissing(appDir: string): Promise<boolean> {
  const gen = join(appDir, "_generated");
  const missingRegistries =
    !(await Bun.file(join(gen, "routes.ts")).exists()) || !(await Bun.file(join(gen, "actions.ts")).exists());
  const missingManifest = !(await Bun.file(join(gen, "manifest.ts")).exists());
  const missingCssTypes = !(await Bun.file(join(gen, "css.d.ts")).exists());
  if (!missingRegistries && !missingManifest && !missingCssTypes) return false;
  if (missingRegistries) await writeModuleRegistries(appDir);
  if (missingManifest) await Bun.write(join(gen, "manifest.ts"), MANIFEST_STUB);
  if (missingCssTypes) await Bun.write(join(gen, "css.d.ts"), CSS_TYPES);
  return true;
}
