import { join } from "node:path";
import { scanRoutes } from "../server/scanner.ts";
import type { Segment } from "../server/scanner.ts";

// Convert [param] / [...catchAll] notation to :param colon-style for URLs.
function patternToColon(urlPattern: string): string {
  if (urlPattern === "") return "/";
  return "/" + urlPattern.split("/").map((seg) => {
    if (seg.startsWith("[...") && seg.endsWith("]")) return ":" + seg.slice(4, -1);
    if (seg.startsWith("[") && seg.endsWith("]")) return ":" + seg.slice(1, -1);
    return seg;
  }).join("/");
}

function paramsFromSegments(segments: Segment[]): string[] {
  return segments.flatMap((seg) =>
    typeof seg === "string" ? [] :
    "param" in seg ? [seg.param] : [seg.catchAll],
  );
}

// Replace each :paramName segment with ${params.paramName} for template literals.
function substituteParams(pattern: string, params: string[]): string {
  const set = new Set(params);
  return pattern.split("/").map((seg) =>
    seg.startsWith(":") && set.has(seg.slice(1))
      ? "${params." + seg.slice(1) + "}"
      : seg,
  ).join("/");
}

function builderEntry(pattern: string, params: string[]): string {
  if (params.length === 0)
    return "  \"" + pattern + "\": () => \"" + pattern + "\" as const,";
  const paramType = params.map((p) => p + ": string").join("; ");
  const body = substituteParams(pattern, params);
  return "  \"" + pattern + "\": (params: { " + paramType + " }) => `" + body + "` as const,";
}

function paramsTypeLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const dynamic = routes.filter((r) => r.params.length > 0);
  if (dynamic.length === 0) return "export type RouteParams<_T extends AppRoutes> = Record<never, never>;";
  const branches = dynamic
    .map((r) =>
      "  T extends \"" + r.pattern + "\" ? { "
      + r.params.map((p) => p + ": string").join("; ")
      + " } :",
    )
    .join("\n");
  return "export type RouteParams<T extends AppRoutes> =\n" + branches + "\n  Record<never, never>;";
}

// Replaced at the top of the generated file.
const HEADER =
  "// Generated by `bractjs codegen` — do not edit manually.\n" +
  "// Re-run with: bunx bractjs codegen\n" +
  "\n" +
  "/* eslint-disable */\n";

export async function generateRouteTypes(appDir: string): Promise<string> {
  const routeFiles = await scanRoutes(appDir);
  const routes = routeFiles.map((r) => ({
    pattern: patternToColon(r.urlPattern),
    params: paramsFromSegments(r.segments),
  }));

  const union = routes.length > 0
    ? routes.map((r) => "  | \"" + r.pattern + "\"").join("\n")
    : "  never";

  const builderEntries = routes.map((r) => builderEntry(r.pattern, r.params)).join("\n");

  return [
    HEADER,
    "export type AppRoutes =",
    union + ";",
    "",
    paramsTypeLines(routes),
    "",
    "export type TypedLoaderArgs<T extends AppRoutes> = {",
    "  request: Request;",
    "  params: RouteParams<T>;",
    "  context: Record<string, unknown>;",
    "};",
    "export type TypedActionArgs<T extends AppRoutes> =",
    "  TypedLoaderArgs<T> & { formData: FormData };",
    "",
    "export const routes = {",
    builderEntries,
    "} as const;",
    "",
  ].join("\n");
}

export async function writeRouteTypes(appDir: string, outPath?: string): Promise<void> {
  const dest = outPath ?? join(appDir, "route-types.gen.ts");
  await Bun.write(dest, await generateRouteTypes(appDir));
  console.log("[bract] codegen →", dest);
}
