import { join } from "node:path";
import { scanRoutes } from "../server/scanner.ts";
import type { Segment } from "../server/scanner.ts";

// Convert [param] / [...catchAll] notation to :param colon-style for URLs.
function patternToColon(urlPattern: string): string {
  if (urlPattern === "") return "/";
  return "/" + urlPattern.split("/").map((seg) => {
    if (seg.startsWith("[...") && seg.endsWith("]")) return ":" + seg.slice(4, -1);
    if (seg.startsWith("[") && seg.endsWith("]")) return ":" + seg.slice(1, -1);
    return seg;
  }).join("/");
}

function paramsFromSegments(segments: Segment[]): string[] {
  return segments.flatMap((seg) =>
    typeof seg === "string" ? [] :
    "param" in seg ? [seg.param] : [seg.catchAll],
  );
}

// Replace each :paramName segment with ${params.paramName} for template literals.
function substituteParams(pattern: string, params: string[]): string {
  const set = new Set(params);
  return pattern.split("/").map((seg) =>
    seg.startsWith(":") && set.has(seg.slice(1))
      ? "${params." + seg.slice(1) + "}"
      : seg,
  ).join("/");
}

// Allowed pattern: "/" + (segment | ":ident") (segments are filename-derived).
// Restricting upfront removes any chance that a hostile filename injects a
// backtick, ${ }, or quote into the generated TS source.
const SAFE_PATTERN_RE = /^\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*)(?:\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*))*$|^\/$/;
const SAFE_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function assertSafePattern(pattern: string): void {
  if (!SAFE_PATTERN_RE.test(pattern)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe route pattern: ${JSON.stringify(pattern)}`);
  }
}
function assertSafeParam(name: string): void {
  if (!SAFE_IDENT_RE.test(name)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe param name: ${JSON.stringify(name)}`);
  }
}

function builderEntry(pattern: string, params: string[]): string {
  assertSafePattern(pattern);
  params.forEach(assertSafeParam);
  const key = JSON.stringify(pattern);
  if (params.length === 0) return "  " + key + ": () => " + key + " as const,";
  const paramType = params.map((p) => p + ": string").join("; ");
  const body = substituteParams(pattern, params);
  return "  " + key + ": (params: { " + paramType + " }) => `" + body + "` as const,";
}

function paramsTypeLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const dynamic = routes.filter((r) => r.params.length > 0);
  if (dynamic.length === 0) return "export type RouteParams<_T extends AppRoutes> = Record<never, never>;";
  const branches = dynamic
    .map((r) => {
      assertSafePattern(r.pattern);
      r.params.forEach(assertSafeParam);
      return "  T extends " + JSON.stringify(r.pattern) + " ? { "
        + r.params.map((p) => p + ": string").join("; ")
        + " } :";
    })
    .join("\n");
  return "export type RouteParams<T extends AppRoutes> =\n" + branches + "\n  Record<never, never>;";
}

// Replaced at the top of the generated file.
const HEADER =
  "// Generated by `bractjs codegen` — do not edit manually.\n" +
  "// Re-run with: bunx bractjs codegen\n" +
  "\n" +
  "/* eslint-disable */\n";

function searchParamsTypeLines(routes: Array<{ pattern: string }>): string {
  // Route files may declare `export type SearchParams = { page: string }`.
  // We emit a mapped type that falls back to Record<string,string> per route.
  // Users augment via module augmentation or via their route file's export.
  if (routes.length === 0) {
    return "export type SearchParams<_T extends AppRoutes> = Record<string, string>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      return "  T extends " + JSON.stringify(r.pattern) + " ? RouteSearchParamsMap[" + JSON.stringify(r.pattern) + "] :";
    })
    .join("\n");
  const mapEntries = routes
    .map((r) => "  " + JSON.stringify(r.pattern) + ": Record<string, string>;")
    .join("\n");
  return [
    "// Augment RouteSearchParamsMap to type search params per route:",
    "// declare module 'bractjs' { interface RouteSearchParamsMap { '/blog': { page: string } } }",
    "export interface RouteSearchParamsMap {",
    mapEntries,
    "}",
    "",
    "export type SearchParams<T extends AppRoutes> =",
    branches,
    "  Record<string, string>;",
  ].join("\n");
}

function contextTypeLines(routes: Array<{ pattern: string }>): string {
  if (routes.length === 0) {
    return "export type Context<_T extends AppRoutes> = Record<string, unknown>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      return "  T extends " + JSON.stringify(r.pattern) + " ? RouteContextMap[" + JSON.stringify(r.pattern) + "] :";
    })
    .join("\n");
  const mapEntries = routes
    .map((r) => "  " + JSON.stringify(r.pattern) + ": Record<string, unknown>;")
    .join("\n");
  return [
    "// Augment RouteContextMap to type context per route:",
    "// declare module 'bractjs' { interface RouteContextMap { '/blog': { user: User } } }",
    "export interface RouteContextMap {",
    mapEntries,
    "}",
    "",
    "export type Context<T extends AppRoutes> =",
    branches,
    "  Record<string, unknown>;",
  ].join("\n");
}

export async function generateRouteTypes(appDir: string): Promise<string> {
  const routeFiles = await scanRoutes(appDir);
  const routes = routeFiles.map((r) => ({
    pattern: patternToColon(r.urlPattern),
    params: paramsFromSegments(r.segments),
  }));

  const union = routes.length > 0
    ? routes.map((r) => {
        assertSafePattern(r.pattern);
        return "  | " + JSON.stringify(r.pattern);
      }).join("\n")
    : "  never";

  const builderEntries = routes.map((r) => builderEntry(r.pattern, r.params)).join("\n");

  return [
    HEADER,
    "export type AppRoutes =",
    union + ";",
    "",
    paramsTypeLines(routes),
    "",
    searchParamsTypeLines(routes),
    "",
    contextTypeLines(routes),
    "",
    "export type TypedLoaderArgs<T extends AppRoutes> = {",
    "  request: Request;",
    "  params: RouteParams<T>;",
    "  context: Context<T>;",
    "};",
    "export type TypedActionArgs<T extends AppRoutes> =",
    "  TypedLoaderArgs<T> & { formData: FormData };",
    "",
    "/** A locale-prefixed variant of a route (E2 i18n routing). */",
    "export type LocalizedRoute<T extends AppRoutes> = `/${string}${T}`;",
    "",
    "export const routes = {",
    builderEntries,
    "} as const;",
    "",
  ].join("\n");
}

export async function writeRouteTypes(appDir: string, outPath?: string): Promise<void> {
  const dest = outPath ?? join(appDir, "route-types.gen.ts");
  await Bun.write(dest, await generateRouteTypes(appDir));
  console.log("[bract] codegen →", dest);
}
