import { join } from "node:path";
import { scanRoutes } from "../server/scanner.ts";
import type { Segment } from "../server/scanner.ts";

// Convert [param] / [...catchAll] notation to :param colon-style for URLs.
function patternToColon(urlPattern: string): string {
  if (urlPattern === "") return "/";
  return "/" + urlPattern.split("/").map((seg) => {
    if (seg.startsWith("[...") && seg.endsWith("]")) return ":" + seg.slice(4, -1);
    if (seg.startsWith("[") && seg.endsWith("]")) return ":" + seg.slice(1, -1);
    return seg;
  }).join("/");
}

function paramsFromSegments(segments: Segment[]): string[] {
  return segments.flatMap((seg) =>
    typeof seg === "string" ? [] :
    "param" in seg ? [seg.param] : [seg.catchAll],
  );
}

// Replace each :paramName segment with ${params.paramName} for template literals.
function substituteParams(pattern: string, params: string[]): string {
  const set = new Set(params);
  return pattern.split("/").map((seg) =>
    seg.startsWith(":") && set.has(seg.slice(1))
      ? "${params." + seg.slice(1) + "}"
      : seg,
  ).join("/");
}

// Allowed pattern: "/" + (segment | ":ident") (segments are filename-derived).
// Restricting upfront removes any chance that a hostile filename injects a
// backtick, ${ }, or quote into the generated TS source.
const SAFE_PATTERN_RE = /^\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*)(?:\/(?:[A-Za-z0-9_\-]+|:[A-Za-z_][A-Za-z0-9_]*))*$|^\/$/;
const SAFE_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function assertSafePattern(pattern: string): void {
  if (!SAFE_PATTERN_RE.test(pattern)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe route pattern: ${JSON.stringify(pattern)}`);
  }
}
function assertSafeParam(name: string): void {
  if (!SAFE_IDENT_RE.test(name)) {
    throw new Error(`[bractjs] codegen: refusing to emit unsafe param name: ${JSON.stringify(name)}`);
  }
}

function builderEntry(pattern: string, params: string[]): string {
  assertSafePattern(pattern);
  params.forEach(assertSafeParam);
  const key = JSON.stringify(pattern);
  if (params.length === 0) return "  " + key + ": () => " + key + " as const,";
  const paramType = params.map((p) => p + ": string").join("; ");
  const body = substituteParams(pattern, params);
  return "  " + key + ": (params: { " + paramType + " }) => `" + body + "` as const,";
}

function paramsTypeLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const dynamic = routes.filter((r) => r.params.length > 0);
  if (dynamic.length === 0) return "export type RouteParams<_T extends AppRoutes> = Record<never, never>;";
  const branches = dynamic
    .map((r) => {
      assertSafePattern(r.pattern);
      r.params.forEach(assertSafeParam);
      return "  T extends " + JSON.stringify(r.pattern) + " ? { "
        + r.params.map((p) => p + ": string").join("; ")
        + " } :";
    })
    .join("\n");
  return "export type RouteParams<T extends AppRoutes> =\n" + branches + "\n  Record<never, never>;";
}

// Replaced at the top of the generated file.
const HEADER =
  "// Generated by `bractjs codegen` — do not edit manually.\n" +
  "// Re-run with: bunx bractjs codegen\n" +
  "\n" +
  "/* eslint-disable */\n";

// `RouteSearchParamsMap` / `RouteContextMap` are owned by the package
// (`@bractjs/bractjs`) so users have a single stable module to augment. We do
// NOT seed per-route keys here: seeding `"/posts": Record<string,string>` would
// conflict with a user augmentation declaring `"/posts": { page: string }`
// (duplicate-property error). Instead `SearchParams<T>` / `Context<T>` fall back
// to the permissive default for any route the user hasn't augmented.
function searchParamsTypeLines(routes: Array<{ pattern: string }>): string {
  if (routes.length === 0) {
    return "export type SearchParams<_T extends AppRoutes> = Record<string, string>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      const key = JSON.stringify(r.pattern);
      // Use `extends Record<K, infer V>` rather than `keyof` + index access:
      // RouteSearchParamsMap may be `{}` (no user augmentation), and indexing an
      // empty interface — even inside a `K extends keyof M` guard — trips
      // TS2538 "cannot be used as an index type". The Record-infer form resolves
      // V only when the route is augmented, and falls back otherwise.
      return "  T extends " + key +
        " ? (RouteSearchParamsMap extends Record<" + key + ", infer V> ? V : Record<string, string>) :";
    })
    .join("\n");
  return [
    "// Augment RouteSearchParamsMap (on the package) to type a route's search params:",
    "//   declare module \"@bractjs/bractjs\" { interface RouteSearchParamsMap { \"/blog\": { page: string } } }",
    "export type SearchParams<T extends AppRoutes> =",
    branches,
    "  Record<string, string>;",
  ].join("\n");
}

function contextTypeLines(routes: Array<{ pattern: string }>): string {
  if (routes.length === 0) {
    return "export type Context<_T extends AppRoutes> = Record<string, unknown>;";
  }
  const branches = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      const key = JSON.stringify(r.pattern);
      // See SearchParams above for why this uses `extends Record<K, infer V>`.
      return "  T extends " + key +
        " ? (RouteContextMap extends Record<" + key + ", infer V> ? V : Record<string, unknown>) :";
    })
    .join("\n");
  return [
    "// Augment RouteContextMap (on the package) to type a route's context:",
    "//   declare module \"@bractjs/bractjs\" { interface RouteContextMap { \"/blog\": { user: User } } }",
    "export type Context<T extends AppRoutes> =",
    branches,
    "  Record<string, unknown>;",
  ].join("\n");
}

// The `Register` augmentation: this is what wires the app's routes into the
// package's runtime helpers (<Link>, useNavigate, useParams, useSearchParams).
function registerAugmentationLines(routes: Array<{ pattern: string; params: string[] }>): string {
  const paramEntries = routes
    .map((r) => {
      assertSafePattern(r.pattern);
      r.params.forEach(assertSafeParam);
      const shape = r.params.length === 0
        ? "{}"
        : "{ " + r.params.map((p) => p + ": string").join("; ") + " }";
      return "      " + JSON.stringify(r.pattern) + ": " + shape + ";";
    })
    .join("\n");
  return [
    "// Registers this app's routes with BractJS. After this augmentation, <Link>,",
    "// useNavigate, useParams, and useSearchParams are type-safe against AppRoutes.",
    "declare module \"@bractjs/bractjs\" {",
    "  interface Register {",
    "    routes: {",
    "      routes: AppRoutes;",
    "      params: {",
    paramEntries,
    "      };",
    "      search: RouteSearchParamsMap;",
    "    };",
    "  }",
    "}",
  ].join("\n");
}

export async function generateRouteTypes(appDir: string): Promise<string> {
  const routeFiles = await scanRoutes(appDir);
  const routes = routeFiles.map((r) => ({
    pattern: patternToColon(r.urlPattern),
    params: paramsFromSegments(r.segments),
  }));

  const union = routes.length > 0
    ? routes.map((r) => {
        assertSafePattern(r.pattern);
        return "  | " + JSON.stringify(r.pattern);
      }).join("\n")
    : "  never";

  const builderEntries = routes.map((r) => builderEntry(r.pattern, r.params)).join("\n");

  // `RouteSearchParamsMap` / `RouteContextMap` are imported from the package so
  // the local `SearchParams<T>` / `Context<T>` reference the same interfaces the
  // user augments via `declare module "@bractjs/bractjs"`.
  const IMPORTS = 'import type { RouteSearchParamsMap, RouteContextMap } from "@bractjs/bractjs";';

  return [
    HEADER,
    IMPORTS,
    "",
    "export type AppRoutes =",
    union + ";",
    "",
    paramsTypeLines(routes),
    "",
    searchParamsTypeLines(routes),
    "",
    contextTypeLines(routes),
    "",
    "export type TypedLoaderArgs<T extends AppRoutes> = {",
    "  request: Request;",
    "  params: RouteParams<T>;",
    "  context: Context<T>;",
    "};",
    "export type TypedActionArgs<T extends AppRoutes> =",
    "  TypedLoaderArgs<T> & { formData: FormData };",
    "",
    "/** A locale-prefixed variant of a route (E2 i18n routing). */",
    "export type LocalizedRoute<T extends AppRoutes> = `/${string}${T}`;",
    "",
    "export const routes = {",
    builderEntries,
    "} as const;",
    "",
    // No routes → AppRoutes is `never`; nothing to register.
    routes.length > 0 ? registerAugmentationLines(routes) : "",
    "",
  ].join("\n");
}

export async function writeRouteTypes(appDir: string, outPath?: string): Promise<void> {
  const dest = outPath ?? join(appDir, "route-types.gen.ts");
  await Bun.write(dest, await generateRouteTypes(appDir));
  console.log("[bract] codegen →", dest);
}
