/**
 * @bractjs/bractjs — public API barrel.
 *
 * Every symbol exported here is public. The published declarations under
 * `types/` are GENERATED from this file's module graph — run
 * `bun run typegen` after changing any public signature and commit the
 * result (CI fails on a stale tree). Section-by-section usage docs live in
 * the repository README: https://github.com/bractjs/bractjs#readme
 */
export { createCloudflareAdapter, makeCloudflareHandler } from "./adapters/cloudflare.ts";
export { buildPath, generatePath, generatePath as href } from "./client/build-path.ts";
export { Await, useAsyncError, useAsyncValue } from "./client/components/Await.tsx";
export { Form } from "./client/components/Form.tsx";
export { Links, Meta, PrefetchPageLinks } from "./client/components/Head.tsx";
export type { ImageFit, ImageFormat, ImageProps } from "./client/components/Image.tsx";
export { Image } from "./client/components/Image.tsx";
export type { LinkProps } from "./client/components/Link.tsx";
export { Link } from "./client/components/Link.tsx";
export { LiveReload } from "./client/components/LiveReload.tsx";
export type { NavigateProps } from "./client/components/Navigate.tsx";
export { Navigate } from "./client/components/Navigate.tsx";
export type { NavLinkProps, NavLinkRenderProps } from "./client/components/NavLink.tsx";
export { NavLink } from "./client/components/NavLink.tsx";
export type { OutletProps } from "./client/components/Outlet.tsx";
export { Outlet, useOutletContext } from "./client/components/Outlet.tsx";
export { Scripts } from "./client/components/Scripts.tsx";
export type { ScrollRestorationProps } from "./client/components/ScrollRestoration.tsx";
export { ScrollRestoration } from "./client/components/ScrollRestoration.tsx";
export type { ToasterProps, ToastPosition } from "./client/components/Toaster.tsx";
export { Toaster } from "./client/components/Toaster.tsx";
export type { FetcherEntry, FetcherState } from "./client/fetcher-store.ts";
export { useFormAction, useHref, useNavigationType, useResolvedPath } from "./client/hooks/compat.ts";
export { useActionData } from "./client/hooks/useActionData.ts";
export type { Blocker, BlockerFunction, BlockerFunctionArgs, HistoryAction, } from "./client/hooks/useBlocker.ts";
export { useBlocker } from "./client/hooks/useBlocker.ts";
export type { FetcherFormProps, FetcherRequest, FetcherResult, StreamFetcherResult, UseFetcherOptions, } from "./client/hooks/useFetcher.ts";
export { useFetcher } from "./client/hooks/useFetcher.ts";
export { useFetchers } from "./client/hooks/useFetchers.ts";
export { useLoaderData } from "./client/hooks/useLoaderData.ts";
export { useLocale } from "./client/hooks/useLocale.ts";
export { useLocalizedLink } from "./client/hooks/useLocalizedLink.ts";
export { useLocation } from "./client/hooks/useLocation.ts";
export { useMatches } from "./client/hooks/useMatches.ts";
export type { NavigateFn, NavigateOptions } from "./client/hooks/useNavigate.ts";
export { useNavigate } from "./client/hooks/useNavigate.ts";
export type { Navigation } from "./client/hooks/useNavigation.ts";
export { useNavigation } from "./client/hooks/useNavigation.ts";
export { useParams } from "./client/hooks/useParams.ts";
export type { Revalidator } from "./client/hooks/useRevalidator.ts";
export { useRevalidator } from "./client/hooks/useRevalidator.ts";
export { useRouteLoaderData } from "./client/hooks/useRouteLoaderData.ts";
export type { SetSearchFn, SetSearchOptions } from "./client/hooks/useSearch.ts";
export { useSearch, useSetSearch } from "./client/hooks/useSearch.ts";
export type { SearchParamsResult, SetSearchParamsOptions, URLSearchParamsInit, } from "./client/hooks/useSearchParams.ts";
export { createSearchParams, useSearchParams } from "./client/hooks/useSearchParams.ts";
export type { SubmitFunction } from "./client/hooks/useSubmit.ts";
export { useSubmit } from "./client/hooks/useSubmit.ts";
export { useToast, useToasts } from "./client/hooks/useToast.ts";
export type { InferSchemaOutput, ParamsFor, Register, RegisteredRouteIds, RegisteredRouteModules, RegisteredRoutes, RouteActionData, RouteContextMap, RouteLoaderData, RouteRegistry, RouteSearchParamsMap, SearchFor, SearchOutputFor, } from "./client/registry.ts";
export { createClient } from "./client/rpc.ts";
export { serializeSearch } from "./client/search-serializer.ts";
export type { SubmitEncType, SubmitOptions, SubmitTarget } from "./client/submission.ts";
export type { Toast, ToastAction, ToastEntry, ToastOptions, ToastType } from "./client/toast-store.ts";
export { toast } from "./client/toast-store.ts";
export { defineConfig, loadUserConfig } from "./config/load.ts";
export type { DevServer, DevServerOptions } from "./dev/server.ts";
export { createDevServer } from "./dev/server.ts";
export type { AuthGuardOptions, SessionLike, SessionStorageLike } from "./middleware/authGuard.ts";
export { authGuard } from "./middleware/authGuard.ts";
export type { CorsOptions } from "./middleware/cors.ts";
export { cors } from "./middleware/cors.ts";
export type { HealthCheckOptions } from "./middleware/healthCheck.ts";
export { healthCheck } from "./middleware/healthCheck.ts";
export type { RateLimiter, RateLimiterOptions, RateLimitOptions, RateLimitResult, RateLimitStore, RateLimitWindow, } from "./middleware/rateLimit.ts";
export { createRateLimiter, memoryRateLimitStore, rateLimit } from "./middleware/rateLimit.ts";
export type { RequestIdOptions } from "./middleware/requestId.ts";
export { requestId } from "./middleware/requestId.ts";
export type { RequestLoggerOptions } from "./middleware/requestLogger.ts";
export { requestLogger } from "./middleware/requestLogger.ts";
export type { SecureHeadersOptions } from "./middleware/secureHeaders.ts";
export { secureHeaders } from "./middleware/secureHeaders.ts";
export type { BractAdapter } from "./server/adapter.ts";
export { BunAdapter } from "./server/adapter.ts";
export type { ApiRouteDefinition, ApiRouteOptions, AppApiRoutes } from "./server/api-route.ts";
export { route } from "./server/api-route.ts";
export type { ContextFactory } from "./server/context.ts";
export { defineContext } from "./server/context.ts";
export type { CspOptions } from "./server/csp.ts";
export { CSP_NONCE_KEY, csp, getCspNonce } from "./server/csp.ts";
export { localizedDataPath, stripLocale, wrapRoutesWithLocale } from "./server/i18n.ts";
export { LOCALE_COOKIE, localizePath, negotiateLocale, splitLocale } from "./shared/i18n.ts";
export type { HandlerInstrumentations, InstrumentCall, Instrumentation, InstrumentRequestInfo, InstrumentResult, InstrumentRouteInfo, RouteInstrumentations, } from "./server/instrumentation.ts";
export { clearInstrumentations, instrument } from "./server/instrumentation.ts";
export type { BractJSConfig, RenderOptions, ServerManifest } from "./server/index.ts";
export { createServer, error, json, redirect, renderRoute } from "./server/index.ts";
export { redirectDocument, replace } from "./server/response.ts";
export type { ModuleRegistry } from "./server/layout.ts";
export type { LifecycleHooks } from "./server/lifecycle.ts";
export { defineLifecycle } from "./server/lifecycle.ts";
export type { MiddlewareContext, MiddlewareFn, RouteMiddleware } from "./server/middleware.ts";
export { createMiddlewareContext, MiddlewarePipeline, pipeline } from "./server/middleware.ts";
export { getRequest, getRequestId } from "./server/request-context.ts";
export { useRequestId } from "./shared/request-id.ts";
export type { ClientAddressOptions } from "./server/client-address.ts";
export { getClientAddress } from "./server/client-address.ts";
export type { RouteFile, Segment } from "./server/scanner.ts";
export { searchParamsToObject, validateSearch } from "./server/search.ts";
export type { I18nConfig } from "./server/serve.ts";
export { buildFetchHandler } from "./server/serve.ts";
export type { CommitOptions, CookieSessionOptions, CookieSessionStorage, CookieSessionStorageOptions, Session, SessionData, SessionDataStrategy, SessionStorage, SessionStorageOptions, } from "./server/session.ts";
export { createCookieSession, createCookieSessionStorage, createMemorySessionStorage, createSessionStorage, } from "./server/session.ts";
export { renderSpaShell } from "./server/spa.ts";
export type { FieldErrors, SafeValidateResult } from "./server/validate.ts";
export { isValidationResponse, readValidationError, safeValidate, ValidationError, validate, } from "./server/validate.ts";
export type { BractJSContextValue, RouteManifest } from "./shared/context.ts";
export { BractJSContext, BractJSProvider, useBractJSContext } from "./shared/context.ts";
export { DataWithResponseInit, data } from "./shared/data.ts";
export { Deferred, defer, isDeferred } from "./shared/deferred.ts";
export { defineActions } from "./shared/define-actions.ts";
export { BractJSError, HttpError, isBractJSError, isHttpError, isRedirect, isRouteErrorResponse, } from "./shared/errors.ts";
export { useRouteError } from "./shared/route-error.ts";
export type { ContextAccessors, RouteContext, RouterContext } from "./shared/router-context.ts";
export { createContext, createContext as unstable_createContext, RouterContextProvider, RouterContextProvider as unstable_RouterContextProvider, } from "./shared/router-context.ts";
export { formText, formValues } from "./shared/form-data.ts";
export type { ActionArgs, ActionData, ActionFunction, ActionFunctionArgs, ClientActionFunction, ClientActionFunctionArgs, ClientLoaderFunction, ClientMiddlewareFunction, ClientLoaderFunctionArgs, ErrorBoundaryProps, HeadersArgs, HeadersFunction, LinkDescriptor, LinksFunction, LoaderArgs, LoaderData, LoaderFunction, LoaderFunctionArgs, MetaArgs, MetaDescriptor, MetaFunction, MetaMatch, MiddlewareFunction, RouteComponentProps, RouteDefinition, RouteMatch, RouteMiddlewareFunction, RouteModule, RouterLocation, ShouldRevalidateArgs, ShouldRevalidateFunction, ShouldRevalidateFunctionArgs, } from "./shared/route-types.ts";
